package com.tgt.trans.dmo.common.examples.saved.output

import io.mockk.every
import io.mockk.mockk
import io.mockk.justRun
import com.tgt.trans.dmo.common.generation.Box
import java.math.BigDecimal

// generated by com.tgt.trans.dmo.common:kotests-generator
class MockkBoxWithModifiedFields {
    fun get(): Box {
        val ret = mockk<Box>()

        every {
            ret.height
        } returns
                BigDecimal("40")

        every {
            ret.length
        } returns
                BigDecimal("41")

        every {
            ret.volume
        } returns
                BigDecimal("42")

        every {
            ret.width
        } returns
                BigDecimal("43")

        every {
            ret.flipOverLength(
            )
        } returns
                Box(
                    length = BigDecimal("4"),
                    width = BigDecimal("5"),
                    height = BigDecimal("6")
                )

        return ret
    }
}